spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
        show_sql: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    hanu:
      exam:
        spring_template: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG
      hibernate:
        type:
          descriptor:
            sql: TRACE
        resource:
          transaction: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true

hanu:
  jwt:
    authorization-header: Authorization
    header-name: Bearer
    access-token:
      secret-key: sebure-access-key-20220712
      expire-length: 10000
    refresh-token:
      secret-key: sebure-refresh-key-20220712
      expire-length: 10000
  security:
    permit-all:
      getList:
        - /api/v1/account/test
        - /account/test
      postList:
        - /api/v1/account/test


