### 로그인
POST http://{{host}}:{{port}}/login
Content-Type: application/json

{
  "username": "test1",
  "password": "1234"
}

> {% //response handler
client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
client.log(response.body.result.accessToken);
client.global.set("access_token", response.body.result.accessToken);
%}

### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "test99",
  "password": "1234"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### 자기정보조회
GET http://localhost:8080/account
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}